package github

import (
	"encoding/json"
	"fmt"
	"os/exec"
	"strconv"
	"strings"
)

// PR represents a GitHub pull request.
type PR struct {
	Number int
	URL    string
}

// PROptions configures a pull request to create.
type PROptions struct {
	RepoSlug string   // e.g. "owncloud/web-extensions"
	Branch   string   // source branch name
	Title    string   // PR title
	Body     string   // PR body (markdown)
	Labels   []string // label names
	Draft    bool     // open as a draft PR
}

// Create opens a pull request via the gh CLI.
// Requires GH_TOKEN or GITHUB_TOKEN in the environment (or gh auth login).
// The `gh` CLI must be installed and authenticated.
func Create(opts PROptions) (*PR, error) {
	args := []string{
		"pr", "create",
		"--repo", opts.RepoSlug,
		"--head", opts.Branch,
		"--title", opts.Title,
		"--body", opts.Body,
	}
	for _, label := range opts.Labels {
		args = append(args, "--label", label)
	}
	if opts.Draft {
		args = append(args, "--draft")
	}

	cmd := exec.Command("gh", args...)
	out, err := cmd.Output()
	if err != nil {
		stderr := ""
		if ee, ok := err.(*exec.ExitError); ok {
			stderr = string(ee.Stderr)
		}
		return nil, fmt.Errorf("gh pr create: %w\nstderr: %s", err, strings.TrimSpace(stderr))
	}

	// gh pr create outputs the PR URL as the last line of stdout
	prURL := strings.TrimSpace(string(out))
	if lines := strings.Split(prURL, "\n"); len(lines) > 0 {
		prURL = strings.TrimSpace(lines[len(lines)-1])
	}

	// extract PR number from URL (e.g. https://github.com/org/repo/pull/42)
	parts := strings.Split(prURL, "/")
	if len(parts) == 0 {
		return nil, fmt.Errorf("parse gh pr create output: unexpected URL %q", prURL)
	}
	prNumber, err := strconv.Atoi(parts[len(parts)-1])
	if err != nil {
		return nil, fmt.Errorf("parse gh pr create output: non-numeric PR number in URL %q", prURL)
	}
	return &PR{Number: prNumber, URL: prURL}, nil
}

// IsMerged reports whether the given PR number has been merged.
func IsMerged(repoSlug string, number int) (bool, error) {
	cmd := exec.Command("gh", "pr", "view",
		fmt.Sprintf("%d", number),
		"--repo", repoSlug,
		"--json", "merged",
	)
	out, err := cmd.Output()
	if err != nil {
		stderr := ""
		if ee, ok := err.(*exec.ExitError); ok {
			stderr = string(ee.Stderr)
		}
		return false, fmt.Errorf("gh pr view: %w\nstderr: %s", err, strings.TrimSpace(stderr))
	}
	var result struct {
		Merged bool `json:"merged"`
	}
	if err := json.Unmarshal(out, &result); err != nil {
		return false, fmt.Errorf("parse gh pr view output: %w", err)
	}
	return result.Merged, nil
}

// AddComment posts a comment on a pull request.
func AddComment(repoSlug string, number int, body string) error {
	cmd := exec.Command("gh", "pr", "comment",
		fmt.Sprintf("%d", number),
		"--repo", repoSlug,
		"--body", body,
	)
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("gh pr comment: %w\n%s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// SetReady marks a draft PR as ready for review.
func SetReady(repoSlug string, number int) error {
	cmd := exec.Command("gh", "pr", "ready",
		fmt.Sprintf("%d", number),
		"--repo", repoSlug,
	)
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("gh pr ready: %w\n%s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// FormatBody renders the PR body per spec §10.
func FormatBody(specMD, whatWasBuilt, jiraKey string, gateScore float64, costUSD float64, turns, attempts int) string {
	var b strings.Builder
	b.WriteString("## Spec\n\n")
	b.WriteString(specMD)
	b.WriteString("\n\n")

	b.WriteString("## What was built\n\n")
	if whatWasBuilt != "" {
		b.WriteString(whatWasBuilt)
	} else {
		b.WriteString("_(build summary unavailable)_")
	}
	b.WriteString("\n\n")

	b.WriteString("## Evidence\n\n")
	b.WriteString("| Acceptance check | Status |\n")
	b.WriteString("|---|---|\n")
	b.WriteString("| See acceptance.spec.ts | gate verified |\n\n")

	b.WriteString("## New dependencies\n\nnone\n\n")

	fmt.Fprintf(&b, "## Links\n\nJira: %s\n\n", jiraKey)

	fmt.Fprintf(&b, "## Pipeline meta\n\ncost $%.2f · turns %d · attempts %d · gate score %.2f\n\n",
		costUSD, turns, attempts, gateScore)

	b.WriteString("🤖 Generated by [extctl](https://github.com/LukasHirt/extctl)\n")
	return b.String()
}
