package marketplace

import (
	"fmt"
	"strings"
)

// FormatPRBody renders the PR body for a marketplace submission. `gh pr
// create --body` fully replaces whatever GitHub would have pre-filled from
// .github/pull_request_template.md, so this renders that template's "oCIS
// web extension" section itself — filled in and checked — rather than an ad
// hoc format a maintainer wouldn't recognize as a proper submission. The
// App/Publisher-page sections are omitted, matching the template's own
// "delete the sections you are not using" instruction.
//
// Most checklist items from the real template are checked unconditionally:
// each one is a property extctl's own code path guarantees by construction
// (BuildSubmission always writes both files at the derived path; the
// version always matches the release directory name it was derived from;
// the id is a deterministic function of appID; Run only ever attempts an
// extension Scan already reported as not yet published; BuildExtensionYAML
// guarantees at least one author). The "at least one tags entry" item is the
// one exception — ResolveTags may legitimately come up with none (no prior
// release, Claude inference failed) rather than inventing a placeholder, so
// that box is only checked when ext.Tags is actually non-empty; otherwise
// it's left unchecked with an explicit note that marketplace CI will reject
// the PR until a human adds real tags. Unlike internal/github's FormatBody
// (AI-candidate specs, Jira links, gate tables — none of which apply here),
// this is a small dedicated renderer.
//
// There is deliberately no "please double-check" section here (there used
// to be one, covering fields extctl had to guess — humanized name, tag/
// minOCIS provenance, missing screenshots). `extctl publish` now stages a
// submission and stops for human review (printReviewNotes prints exactly
// that context to the terminal at staging time) before `extctl publish
// approve` ever runs — by the time a PR exists, a human already decided
// whatever needed deciding, so carrying that context into the PR itself
// would just be noise for a marketplace maintainer who has no way to act
// on it.
func FormatPRBody(r Result, ext ExtensionYAML) string {
	var b strings.Builder

	b.WriteString("## Submit to the ownCloud marketplace\n\n")
	b.WriteString("**What are you submitting?**\n")
	b.WriteString("- [ ] An **app** (ownCloud Classic app)\n")
	b.WriteString("- [x] An **oCIS web extension**\n")
	b.WriteString("- [ ] A **publisher page**\n\n")
	b.WriteString("---\n\n")

	b.WriteString("## oCIS web extension\n\n")
	b.WriteString("A web extension adds a release directory whose metadata is authored in\n")
	b.WriteString("`extension.yaml` (oCIS reads it from the repository feed, not the bundle).\n\n")
	fmt.Fprintf(&b, "- **Extension id** (the reverse-DNS `id` in extension.yaml): `%s`\n", ext.ID)
	fmt.Fprintf(&b, "- **Folder slug** (`<ext-id>`, also the release tag / asset name): `%s`\n", r.AppID)
	fmt.Fprintf(&b, "- **Version** (the `version` in extension.yaml): `%s`\n", ext.Version)
	fmt.Fprintf(&b, "- **Files added:** `extensions/%s/releases/%s/` containing `bundle.zip`\n", r.AppID, ext.Version)
	b.WriteString("  (Git LFS) and `extension.yaml`")
	if len(ext.ScreenshotCaptions) > 0 {
		b.WriteString(" and a `screenshots/` dir")
	}
	b.WriteString(".\n\n")

	b.WriteString("### Checklist\n")
	fmt.Fprintf(&b, "- [x] `bundle.zip` and `extension.yaml` are committed under `extensions/%s/releases/%s/`.\n", r.AppID, ext.Version)
	b.WriteString("- [x] The `version` in `extension.yaml` matches the `releases/<version>/` directory name.\n")
	b.WriteString("- [x] The reverse-DNS `id` is the same across every release of this extension.\n")
	b.WriteString("- [x] This is a **new** release — I am not modifying or deleting an already-published release.\n")
	if len(ext.Tags) > 0 {
		b.WriteString("- [x] `extension.yaml` has at least one `authors` entry and at least one `tags` entry.\n\n")
	} else {
		b.WriteString("- [ ] `extension.yaml` has at least one `authors` entry and at least one `tags` entry — **missing tags**, add at least one directly in `extension.yaml`.\n\n")
	}

	fmt.Fprintf(&b, "Built from [web-extensions release `%s`](https://github.com/owncloud/web-extensions/releases/tag/%s), reviewed locally via `extctl publish` before approval.\n\n", r.Tag, r.Tag)
	b.WriteString("<sub>🤖 Generated by [extctl](https://github.com/LukasHirt/extctl) publish</sub>\n")

	return b.String()
}
