import { defineWebApplication } from '@ownclouders/web-pkg'
import App from './App.vue'

// {{EXT_TITLE}} — generated by extctl
// Extension point: see CANDIDATE spec for details.
export default defineWebApplication({
  setup() {
    // TODO(generated): register extension-point contributions here.
    // Example for files-context-menu:
    // const { $gettext } = useGettext()
    // useExtensionRegistry().registerExtension({
    //   id: '{{EXT_ID}}.context-menu',
    //   type: 'action',
    //   ...
    // })
    return {}
  },

  // Root component mounted by oCIS Web.
  rootComponent: App
})
